name: virtual_keyboard_ex
description: "Virtual keyboard"
version: 0.0.6
homepage: https://github.com/Masum-MSNR/virtual_keyboard_ex
repository: https://github.com/Masum-MSNR/virtual_keyboard_ex
issue_tracker: https://github.com/Masum-MSNR/virtual_keyboard_ex/issues

environment:
#  sdk: ^3.7.2
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/svgs/